[build.env]
passthrough = [
  "RUST_BACKTRACE",
]

# arm32v6
[target.arm-unknown-linux-gnueabi]
image = "jjlin/bitwardenrs-cross:arm-unknown-linux-gnueabi"

# arm32v7
[target.armv7-unknown-linux-gnueabihf]
image = "jjlin/bitwardenrs-cross:armv7-unknown-linux-gnueabihf"
#rustflags = ["-C", "link-arg=-L/usr/lib/arm-linux-gnueabihf"]

# arm64v8
[target.aarch64-unknown-linux-gnu]
image = "jjlin/bitwardenrs-cross:aarch64-unknown-linux-gnu"
